### ISSUE TITLE
Support aarch64

### ISSUE THREAD

**Issue by jsf9k** [geerlingguy/docker-fedora39-ansible#1]
We currently use this Docker image to test our [cisagov](https://github.com/cisagov) Ansible roles.  I am looking to test our Ansible roles on both aarch64 and arm64 platforms, but this image does not support the former.  It would be nice if it did.

**Comment by geerlingguy** [comment]
I agree; I haven't looked into using BuildX to build multi-arch images for these ansible test containers yet. Hopefully it wouldn't be too much of a burden.

**Comment by jsf9k** [comment]
Resolved by #2.
